// AUTO-GENERATED by scripts/fetch-world-atlas.mjs — do not edit by hand.
// numeric ISO 3166-1 (TopoJSON id) -> { iso2, name, region }, plus lookups.

export type CountryMeta = { iso2: string; name: string; region: string }

export const ISO_BY_NUMERIC: Record<string, CountryMeta> = {
  "100": {
    "iso2": "BG",
    "name": "Bulgaria",
    "region": "Europe"
  },
  "104": {
    "iso2": "MM",
    "name": "Myanmar",
    "region": "Asia"
  },
  "108": {
    "iso2": "BI",
    "name": "Burundi",
    "region": "Africa"
  },
  "112": {
    "iso2": "BY",
    "name": "Belarus",
    "region": "Europe"
  },
  "116": {
    "iso2": "KH",
    "name": "Cambodia",
    "region": "Asia"
  },
  "120": {
    "iso2": "CM",
    "name": "Cameroon",
    "region": "Africa"
  },
  "124": {
    "iso2": "CA",
    "name": "Canada",
    "region": "Americas"
  },
  "132": {
    "iso2": "CV",
    "name": "Cape Verde",
    "region": "Africa"
  },
  "136": {
    "iso2": "KY",
    "name": "Cayman Islands",
    "region": "Americas"
  },
  "140": {
    "iso2": "CF",
    "name": "Central African Republic",
    "region": "Africa"
  },
  "144": {
    "iso2": "LK",
    "name": "Sri Lanka",
    "region": "Asia"
  },
  "148": {
    "iso2": "TD",
    "name": "Chad",
    "region": "Africa"
  },
  "152": {
    "iso2": "CL",
    "name": "Chile",
    "region": "Americas"
  },
  "156": {
    "iso2": "CN",
    "name": "China",
    "region": "Asia"
  },
  "158": {
    "iso2": "TW",
    "name": "Taiwan",
    "region": "Asia"
  },
  "162": {
    "iso2": "CX",
    "name": "Christmas Island",
    "region": "Oceania"
  },
  "166": {
    "iso2": "CC",
    "name": "Cocos (Keeling) Islands",
    "region": "Oceania"
  },
  "170": {
    "iso2": "CO",
    "name": "Colombia",
    "region": "Americas"
  },
  "174": {
    "iso2": "KM",
    "name": "Comoros",
    "region": "Africa"
  },
  "175": {
    "iso2": "YT",
    "name": "Mayotte",
    "region": "Africa"
  },
  "178": {
    "iso2": "CG",
    "name": "Republic of the Congo",
    "region": "Africa"
  },
  "180": {
    "iso2": "CD",
    "name": "DR Congo",
    "region": "Africa"
  },
  "184": {
    "iso2": "CK",
    "name": "Cook Islands",
    "region": "Oceania"
  },
  "188": {
    "iso2": "CR",
    "name": "Costa Rica",
    "region": "Americas"
  },
  "191": {
    "iso2": "HR",
    "name": "Croatia",
    "region": "Europe"
  },
  "192": {
    "iso2": "CU",
    "name": "Cuba",
    "region": "Americas"
  },
  "196": {
    "iso2": "CY",
    "name": "Cyprus",
    "region": "Europe"
  },
  "203": {
    "iso2": "CZ",
    "name": "Czechia",
    "region": "Europe"
  },
  "204": {
    "iso2": "BJ",
    "name": "Benin",
    "region": "Africa"
  },
  "208": {
    "iso2": "DK",
    "name": "Denmark",
    "region": "Europe"
  },
  "212": {
    "iso2": "DM",
    "name": "Dominica",
    "region": "Americas"
  },
  "214": {
    "iso2": "DO",
    "name": "Dominican Republic",
    "region": "Americas"
  },
  "218": {
    "iso2": "EC",
    "name": "Ecuador",
    "region": "Americas"
  },
  "222": {
    "iso2": "SV",
    "name": "El Salvador",
    "region": "Americas"
  },
  "226": {
    "iso2": "GQ",
    "name": "Equatorial Guinea",
    "region": "Africa"
  },
  "231": {
    "iso2": "ET",
    "name": "Ethiopia",
    "region": "Africa"
  },
  "232": {
    "iso2": "ER",
    "name": "Eritrea",
    "region": "Africa"
  },
  "233": {
    "iso2": "EE",
    "name": "Estonia",
    "region": "Europe"
  },
  "234": {
    "iso2": "FO",
    "name": "Faroe Islands",
    "region": "Europe"
  },
  "238": {
    "iso2": "FK",
    "name": "Falkland Islands",
    "region": "Americas"
  },
  "239": {
    "iso2": "GS",
    "name": "South Georgia",
    "region": "Antarctic"
  },
  "242": {
    "iso2": "FJ",
    "name": "Fiji",
    "region": "Oceania"
  },
  "246": {
    "iso2": "FI",
    "name": "Finland",
    "region": "Europe"
  },
  "248": {
    "iso2": "AX",
    "name": "Åland Islands",
    "region": "Europe"
  },
  "250": {
    "iso2": "FR",
    "name": "France",
    "region": "Europe"
  },
  "254": {
    "iso2": "GF",
    "name": "French Guiana",
    "region": "Americas"
  },
  "258": {
    "iso2": "PF",
    "name": "French Polynesia",
    "region": "Oceania"
  },
  "260": {
    "iso2": "TF",
    "name": "French Southern and Antarctic Lands",
    "region": "Antarctic"
  },
  "262": {
    "iso2": "DJ",
    "name": "Djibouti",
    "region": "Africa"
  },
  "266": {
    "iso2": "GA",
    "name": "Gabon",
    "region": "Africa"
  },
  "268": {
    "iso2": "GE",
    "name": "Georgia",
    "region": "Asia"
  },
  "270": {
    "iso2": "GM",
    "name": "Gambia",
    "region": "Africa"
  },
  "275": {
    "iso2": "PS",
    "name": "Palestine",
    "region": "Asia"
  },
  "276": {
    "iso2": "DE",
    "name": "Germany",
    "region": "Europe"
  },
  "288": {
    "iso2": "GH",
    "name": "Ghana",
    "region": "Africa"
  },
  "292": {
    "iso2": "GI",
    "name": "Gibraltar",
    "region": "Europe"
  },
  "296": {
    "iso2": "KI",
    "name": "Kiribati",
    "region": "Oceania"
  },
  "300": {
    "iso2": "GR",
    "name": "Greece",
    "region": "Europe"
  },
  "304": {
    "iso2": "GL",
    "name": "Greenland",
    "region": "Americas"
  },
  "308": {
    "iso2": "GD",
    "name": "Grenada",
    "region": "Americas"
  },
  "312": {
    "iso2": "GP",
    "name": "Guadeloupe",
    "region": "Americas"
  },
  "316": {
    "iso2": "GU",
    "name": "Guam",
    "region": "Oceania"
  },
  "320": {
    "iso2": "GT",
    "name": "Guatemala",
    "region": "Americas"
  },
  "324": {
    "iso2": "GN",
    "name": "Guinea",
    "region": "Africa"
  },
  "328": {
    "iso2": "GY",
    "name": "Guyana",
    "region": "Americas"
  },
  "332": {
    "iso2": "HT",
    "name": "Haiti",
    "region": "Americas"
  },
  "334": {
    "iso2": "HM",
    "name": "Heard Island and McDonald Islands",
    "region": "Antarctic"
  },
  "336": {
    "iso2": "VA",
    "name": "Vatican City",
    "region": "Europe"
  },
  "340": {
    "iso2": "HN",
    "name": "Honduras",
    "region": "Americas"
  },
  "344": {
    "iso2": "HK",
    "name": "Hong Kong",
    "region": "Asia"
  },
  "348": {
    "iso2": "HU",
    "name": "Hungary",
    "region": "Europe"
  },
  "352": {
    "iso2": "IS",
    "name": "Iceland",
    "region": "Europe"
  },
  "356": {
    "iso2": "IN",
    "name": "India",
    "region": "Asia"
  },
  "360": {
    "iso2": "ID",
    "name": "Indonesia",
    "region": "Asia"
  },
  "364": {
    "iso2": "IR",
    "name": "Iran",
    "region": "Asia"
  },
  "368": {
    "iso2": "IQ",
    "name": "Iraq",
    "region": "Asia"
  },
  "372": {
    "iso2": "IE",
    "name": "Ireland",
    "region": "Europe"
  },
  "376": {
    "iso2": "IL",
    "name": "Israel",
    "region": "Asia"
  },
  "380": {
    "iso2": "IT",
    "name": "Italy",
    "region": "Europe"
  },
  "384": {
    "iso2": "CI",
    "name": "Ivory Coast",
    "region": "Africa"
  },
  "388": {
    "iso2": "JM",
    "name": "Jamaica",
    "region": "Americas"
  },
  "392": {
    "iso2": "JP",
    "name": "Japan",
    "region": "Asia"
  },
  "398": {
    "iso2": "KZ",
    "name": "Kazakhstan",
    "region": "Asia"
  },
  "400": {
    "iso2": "JO",
    "name": "Jordan",
    "region": "Asia"
  },
  "404": {
    "iso2": "KE",
    "name": "Kenya",
    "region": "Africa"
  },
  "408": {
    "iso2": "KP",
    "name": "North Korea",
    "region": "Asia"
  },
  "410": {
    "iso2": "KR",
    "name": "South Korea",
    "region": "Asia"
  },
  "414": {
    "iso2": "KW",
    "name": "Kuwait",
    "region": "Asia"
  },
  "417": {
    "iso2": "KG",
    "name": "Kyrgyzstan",
    "region": "Asia"
  },
  "418": {
    "iso2": "LA",
    "name": "Laos",
    "region": "Asia"
  },
  "422": {
    "iso2": "LB",
    "name": "Lebanon",
    "region": "Asia"
  },
  "426": {
    "iso2": "LS",
    "name": "Lesotho",
    "region": "Africa"
  },
  "428": {
    "iso2": "LV",
    "name": "Latvia",
    "region": "Europe"
  },
  "430": {
    "iso2": "LR",
    "name": "Liberia",
    "region": "Africa"
  },
  "434": {
    "iso2": "LY",
    "name": "Libya",
    "region": "Africa"
  },
  "438": {
    "iso2": "LI",
    "name": "Liechtenstein",
    "region": "Europe"
  },
  "440": {
    "iso2": "LT",
    "name": "Lithuania",
    "region": "Europe"
  },
  "442": {
    "iso2": "LU",
    "name": "Luxembourg",
    "region": "Europe"
  },
  "446": {
    "iso2": "MO",
    "name": "Macau",
    "region": "Asia"
  },
  "450": {
    "iso2": "MG",
    "name": "Madagascar",
    "region": "Africa"
  },
  "454": {
    "iso2": "MW",
    "name": "Malawi",
    "region": "Africa"
  },
  "458": {
    "iso2": "MY",
    "name": "Malaysia",
    "region": "Asia"
  },
  "462": {
    "iso2": "MV",
    "name": "Maldives",
    "region": "Asia"
  },
  "466": {
    "iso2": "ML",
    "name": "Mali",
    "region": "Africa"
  },
  "470": {
    "iso2": "MT",
    "name": "Malta",
    "region": "Europe"
  },
  "474": {
    "iso2": "MQ",
    "name": "Martinique",
    "region": "Americas"
  },
  "478": {
    "iso2": "MR",
    "name": "Mauritania",
    "region": "Africa"
  },
  "480": {
    "iso2": "MU",
    "name": "Mauritius",
    "region": "Africa"
  },
  "484": {
    "iso2": "MX",
    "name": "Mexico",
    "region": "Americas"
  },
  "492": {
    "iso2": "MC",
    "name": "Monaco",
    "region": "Europe"
  },
  "496": {
    "iso2": "MN",
    "name": "Mongolia",
    "region": "Asia"
  },
  "498": {
    "iso2": "MD",
    "name": "Moldova",
    "region": "Europe"
  },
  "499": {
    "iso2": "ME",
    "name": "Montenegro",
    "region": "Europe"
  },
  "500": {
    "iso2": "MS",
    "name": "Montserrat",
    "region": "Americas"
  },
  "504": {
    "iso2": "MA",
    "name": "Morocco",
    "region": "Africa"
  },
  "508": {
    "iso2": "MZ",
    "name": "Mozambique",
    "region": "Africa"
  },
  "512": {
    "iso2": "OM",
    "name": "Oman",
    "region": "Asia"
  },
  "516": {
    "iso2": "NA",
    "name": "Namibia",
    "region": "Africa"
  },
  "520": {
    "iso2": "NR",
    "name": "Nauru",
    "region": "Oceania"
  },
  "524": {
    "iso2": "NP",
    "name": "Nepal",
    "region": "Asia"
  },
  "528": {
    "iso2": "NL",
    "name": "Netherlands",
    "region": "Europe"
  },
  "531": {
    "iso2": "CW",
    "name": "Curaçao",
    "region": "Americas"
  },
  "533": {
    "iso2": "AW",
    "name": "Aruba",
    "region": "Americas"
  },
  "534": {
    "iso2": "SX",
    "name": "Sint Maarten",
    "region": "Americas"
  },
  "535": {
    "iso2": "BQ",
    "name": "Caribbean Netherlands",
    "region": "Americas"
  },
  "540": {
    "iso2": "NC",
    "name": "New Caledonia",
    "region": "Oceania"
  },
  "548": {
    "iso2": "VU",
    "name": "Vanuatu",
    "region": "Oceania"
  },
  "554": {
    "iso2": "NZ",
    "name": "New Zealand",
    "region": "Oceania"
  },
  "558": {
    "iso2": "NI",
    "name": "Nicaragua",
    "region": "Americas"
  },
  "562": {
    "iso2": "NE",
    "name": "Niger",
    "region": "Africa"
  },
  "566": {
    "iso2": "NG",
    "name": "Nigeria",
    "region": "Africa"
  },
  "570": {
    "iso2": "NU",
    "name": "Niue",
    "region": "Oceania"
  },
  "574": {
    "iso2": "NF",
    "name": "Norfolk Island",
    "region": "Oceania"
  },
  "578": {
    "iso2": "NO",
    "name": "Norway",
    "region": "Europe"
  },
  "580": {
    "iso2": "MP",
    "name": "Northern Mariana Islands",
    "region": "Oceania"
  },
  "581": {
    "iso2": "UM",
    "name": "United States Minor Outlying Islands",
    "region": "Americas"
  },
  "583": {
    "iso2": "FM",
    "name": "Micronesia",
    "region": "Oceania"
  },
  "584": {
    "iso2": "MH",
    "name": "Marshall Islands",
    "region": "Oceania"
  },
  "585": {
    "iso2": "PW",
    "name": "Palau",
    "region": "Oceania"
  },
  "586": {
    "iso2": "PK",
    "name": "Pakistan",
    "region": "Asia"
  },
  "591": {
    "iso2": "PA",
    "name": "Panama",
    "region": "Americas"
  },
  "598": {
    "iso2": "PG",
    "name": "Papua New Guinea",
    "region": "Oceania"
  },
  "600": {
    "iso2": "PY",
    "name": "Paraguay",
    "region": "Americas"
  },
  "604": {
    "iso2": "PE",
    "name": "Peru",
    "region": "Americas"
  },
  "608": {
    "iso2": "PH",
    "name": "Philippines",
    "region": "Asia"
  },
  "612": {
    "iso2": "PN",
    "name": "Pitcairn Islands",
    "region": "Oceania"
  },
  "616": {
    "iso2": "PL",
    "name": "Poland",
    "region": "Europe"
  },
  "620": {
    "iso2": "PT",
    "name": "Portugal",
    "region": "Europe"
  },
  "624": {
    "iso2": "GW",
    "name": "Guinea-Bissau",
    "region": "Africa"
  },
  "626": {
    "iso2": "TL",
    "name": "Timor-Leste",
    "region": "Asia"
  },
  "630": {
    "iso2": "PR",
    "name": "Puerto Rico",
    "region": "Americas"
  },
  "634": {
    "iso2": "QA",
    "name": "Qatar",
    "region": "Asia"
  },
  "638": {
    "iso2": "RE",
    "name": "Réunion",
    "region": "Africa"
  },
  "642": {
    "iso2": "RO",
    "name": "Romania",
    "region": "Europe"
  },
  "643": {
    "iso2": "RU",
    "name": "Russia",
    "region": "Europe"
  },
  "646": {
    "iso2": "RW",
    "name": "Rwanda",
    "region": "Africa"
  },
  "652": {
    "iso2": "BL",
    "name": "Saint Barthélemy",
    "region": "Americas"
  },
  "654": {
    "iso2": "SH",
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "region": "Africa"
  },
  "659": {
    "iso2": "KN",
    "name": "Saint Kitts and Nevis",
    "region": "Americas"
  },
  "660": {
    "iso2": "AI",
    "name": "Anguilla",
    "region": "Americas"
  },
  "662": {
    "iso2": "LC",
    "name": "Saint Lucia",
    "region": "Americas"
  },
  "663": {
    "iso2": "MF",
    "name": "Saint Martin",
    "region": "Americas"
  },
  "666": {
    "iso2": "PM",
    "name": "Saint Pierre and Miquelon",
    "region": "Americas"
  },
  "670": {
    "iso2": "VC",
    "name": "Saint Vincent and the Grenadines",
    "region": "Americas"
  },
  "674": {
    "iso2": "SM",
    "name": "San Marino",
    "region": "Europe"
  },
  "678": {
    "iso2": "ST",
    "name": "São Tomé and Príncipe",
    "region": "Africa"
  },
  "682": {
    "iso2": "SA",
    "name": "Saudi Arabia",
    "region": "Asia"
  },
  "686": {
    "iso2": "SN",
    "name": "Senegal",
    "region": "Africa"
  },
  "688": {
    "iso2": "RS",
    "name": "Serbia",
    "region": "Europe"
  },
  "690": {
    "iso2": "SC",
    "name": "Seychelles",
    "region": "Africa"
  },
  "694": {
    "iso2": "SL",
    "name": "Sierra Leone",
    "region": "Africa"
  },
  "702": {
    "iso2": "SG",
    "name": "Singapore",
    "region": "Asia"
  },
  "703": {
    "iso2": "SK",
    "name": "Slovakia",
    "region": "Europe"
  },
  "704": {
    "iso2": "VN",
    "name": "Vietnam",
    "region": "Asia"
  },
  "705": {
    "iso2": "SI",
    "name": "Slovenia",
    "region": "Europe"
  },
  "706": {
    "iso2": "SO",
    "name": "Somalia",
    "region": "Africa"
  },
  "710": {
    "iso2": "ZA",
    "name": "South Africa",
    "region": "Africa"
  },
  "716": {
    "iso2": "ZW",
    "name": "Zimbabwe",
    "region": "Africa"
  },
  "724": {
    "iso2": "ES",
    "name": "Spain",
    "region": "Europe"
  },
  "728": {
    "iso2": "SS",
    "name": "South Sudan",
    "region": "Africa"
  },
  "729": {
    "iso2": "SD",
    "name": "Sudan",
    "region": "Africa"
  },
  "732": {
    "iso2": "EH",
    "name": "Western Sahara",
    "region": "Africa"
  },
  "740": {
    "iso2": "SR",
    "name": "Suriname",
    "region": "Americas"
  },
  "744": {
    "iso2": "SJ",
    "name": "Svalbard and Jan Mayen",
    "region": "Europe"
  },
  "748": {
    "iso2": "SZ",
    "name": "Eswatini",
    "region": "Africa"
  },
  "752": {
    "iso2": "SE",
    "name": "Sweden",
    "region": "Europe"
  },
  "756": {
    "iso2": "CH",
    "name": "Switzerland",
    "region": "Europe"
  },
  "760": {
    "iso2": "SY",
    "name": "Syria",
    "region": "Asia"
  },
  "762": {
    "iso2": "TJ",
    "name": "Tajikistan",
    "region": "Asia"
  },
  "764": {
    "iso2": "TH",
    "name": "Thailand",
    "region": "Asia"
  },
  "768": {
    "iso2": "TG",
    "name": "Togo",
    "region": "Africa"
  },
  "772": {
    "iso2": "TK",
    "name": "Tokelau",
    "region": "Oceania"
  },
  "776": {
    "iso2": "TO",
    "name": "Tonga",
    "region": "Oceania"
  },
  "780": {
    "iso2": "TT",
    "name": "Trinidad and Tobago",
    "region": "Americas"
  },
  "784": {
    "iso2": "AE",
    "name": "United Arab Emirates",
    "region": "Asia"
  },
  "788": {
    "iso2": "TN",
    "name": "Tunisia",
    "region": "Africa"
  },
  "792": {
    "iso2": "TR",
    "name": "Türkiye",
    "region": "Asia"
  },
  "795": {
    "iso2": "TM",
    "name": "Turkmenistan",
    "region": "Asia"
  },
  "796": {
    "iso2": "TC",
    "name": "Turks and Caicos Islands",
    "region": "Americas"
  },
  "798": {
    "iso2": "TV",
    "name": "Tuvalu",
    "region": "Oceania"
  },
  "800": {
    "iso2": "UG",
    "name": "Uganda",
    "region": "Africa"
  },
  "804": {
    "iso2": "UA",
    "name": "Ukraine",
    "region": "Europe"
  },
  "807": {
    "iso2": "MK",
    "name": "North Macedonia",
    "region": "Europe"
  },
  "818": {
    "iso2": "EG",
    "name": "Egypt",
    "region": "Africa"
  },
  "826": {
    "iso2": "GB",
    "name": "United Kingdom",
    "region": "Europe"
  },
  "831": {
    "iso2": "GG",
    "name": "Guernsey",
    "region": "Europe"
  },
  "832": {
    "iso2": "JE",
    "name": "Jersey",
    "region": "Europe"
  },
  "833": {
    "iso2": "IM",
    "name": "Isle of Man",
    "region": "Europe"
  },
  "834": {
    "iso2": "TZ",
    "name": "Tanzania",
    "region": "Africa"
  },
  "840": {
    "iso2": "US",
    "name": "United States",
    "region": "Americas"
  },
  "850": {
    "iso2": "VI",
    "name": "United States Virgin Islands",
    "region": "Americas"
  },
  "854": {
    "iso2": "BF",
    "name": "Burkina Faso",
    "region": "Africa"
  },
  "858": {
    "iso2": "UY",
    "name": "Uruguay",
    "region": "Americas"
  },
  "860": {
    "iso2": "UZ",
    "name": "Uzbekistan",
    "region": "Asia"
  },
  "862": {
    "iso2": "VE",
    "name": "Venezuela",
    "region": "Americas"
  },
  "876": {
    "iso2": "WF",
    "name": "Wallis and Futuna",
    "region": "Oceania"
  },
  "882": {
    "iso2": "WS",
    "name": "Samoa",
    "region": "Oceania"
  },
  "887": {
    "iso2": "YE",
    "name": "Yemen",
    "region": "Asia"
  },
  "894": {
    "iso2": "ZM",
    "name": "Zambia",
    "region": "Africa"
  },
  "004": {
    "iso2": "AF",
    "name": "Afghanistan",
    "region": "Asia"
  },
  "024": {
    "iso2": "AO",
    "name": "Angola",
    "region": "Africa"
  },
  "008": {
    "iso2": "AL",
    "name": "Albania",
    "region": "Europe"
  },
  "020": {
    "iso2": "AD",
    "name": "Andorra",
    "region": "Europe"
  },
  "032": {
    "iso2": "AR",
    "name": "Argentina",
    "region": "Americas"
  },
  "051": {
    "iso2": "AM",
    "name": "Armenia",
    "region": "Asia"
  },
  "016": {
    "iso2": "AS",
    "name": "American Samoa",
    "region": "Oceania"
  },
  "010": {
    "iso2": "AQ",
    "name": "Antarctica",
    "region": "Antarctic"
  },
  "028": {
    "iso2": "AG",
    "name": "Antigua and Barbuda",
    "region": "Americas"
  },
  "036": {
    "iso2": "AU",
    "name": "Australia",
    "region": "Oceania"
  },
  "040": {
    "iso2": "AT",
    "name": "Austria",
    "region": "Europe"
  },
  "031": {
    "iso2": "AZ",
    "name": "Azerbaijan",
    "region": "Asia"
  },
  "056": {
    "iso2": "BE",
    "name": "Belgium",
    "region": "Europe"
  },
  "050": {
    "iso2": "BD",
    "name": "Bangladesh",
    "region": "Asia"
  },
  "048": {
    "iso2": "BH",
    "name": "Bahrain",
    "region": "Asia"
  },
  "044": {
    "iso2": "BS",
    "name": "Bahamas",
    "region": "Americas"
  },
  "070": {
    "iso2": "BA",
    "name": "Bosnia and Herzegovina",
    "region": "Europe"
  },
  "084": {
    "iso2": "BZ",
    "name": "Belize",
    "region": "Americas"
  },
  "060": {
    "iso2": "BM",
    "name": "Bermuda",
    "region": "Americas"
  },
  "068": {
    "iso2": "BO",
    "name": "Bolivia",
    "region": "Americas"
  },
  "076": {
    "iso2": "BR",
    "name": "Brazil",
    "region": "Americas"
  },
  "052": {
    "iso2": "BB",
    "name": "Barbados",
    "region": "Americas"
  },
  "096": {
    "iso2": "BN",
    "name": "Brunei",
    "region": "Asia"
  },
  "064": {
    "iso2": "BT",
    "name": "Bhutan",
    "region": "Asia"
  },
  "074": {
    "iso2": "BV",
    "name": "Bouvet Island",
    "region": "Antarctic"
  },
  "072": {
    "iso2": "BW",
    "name": "Botswana",
    "region": "Africa"
  },
  "012": {
    "iso2": "DZ",
    "name": "Algeria",
    "region": "Africa"
  },
  "086": {
    "iso2": "IO",
    "name": "British Indian Ocean Territory",
    "region": "Africa"
  },
  "090": {
    "iso2": "SB",
    "name": "Solomon Islands",
    "region": "Oceania"
  },
  "092": {
    "iso2": "VG",
    "name": "British Virgin Islands",
    "region": "Americas"
  },
  "undefined": {
    "iso2": "XU",
    "name": "N. Cyprus",
    "region": "Other"
  }
}

/** ISO 3166-1 alpha-2 (UPPERCASE) -> common name. */
export const COUNTRY_NAME: Record<string, string> = {
  "BG": "Bulgaria",
  "MM": "Myanmar",
  "BI": "Burundi",
  "BY": "Belarus",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "LK": "Sri Lanka",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "TW": "Taiwan",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "YT": "Mayotte",
  "CG": "Republic of the Congo",
  "CD": "DR Congo",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "HR": "Croatia",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "BJ": "Benin",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ET": "Ethiopia",
  "ER": "Eritrea",
  "EE": "Estonia",
  "FO": "Faroe Islands",
  "FK": "Falkland Islands",
  "GS": "South Georgia",
  "FJ": "Fiji",
  "FI": "Finland",
  "AX": "Åland Islands",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern and Antarctic Lands",
  "DJ": "Djibouti",
  "GA": "Gabon",
  "GE": "Georgia",
  "GM": "Gambia",
  "PS": "Palestine",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "KI": "Kiribati",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GN": "Guinea",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island and McDonald Islands",
  "VA": "Vatican City",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IL": "Israel",
  "IT": "Italy",
  "CI": "Ivory Coast",
  "JM": "Jamaica",
  "JP": "Japan",
  "KZ": "Kazakhstan",
  "JO": "Jordan",
  "KE": "Kenya",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LV": "Latvia",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macau",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "MX": "Mexico",
  "MC": "Monaco",
  "MN": "Mongolia",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "OM": "Oman",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "CW": "Curaçao",
  "AW": "Aruba",
  "SX": "Sint Maarten",
  "BQ": "Caribbean Netherlands",
  "NC": "New Caledonia",
  "VU": "Vanuatu",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "NO": "Norway",
  "MP": "Northern Mariana Islands",
  "UM": "United States Minor Outlying Islands",
  "FM": "Micronesia",
  "MH": "Marshall Islands",
  "PW": "Palau",
  "PK": "Pakistan",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn Islands",
  "PL": "Poland",
  "PT": "Portugal",
  "GW": "Guinea-Bissau",
  "TL": "Timor-Leste",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RU": "Russia",
  "RW": "Rwanda",
  "BL": "Saint Barthélemy",
  "SH": "Saint Helena, Ascension and Tristan da Cunha",
  "KN": "Saint Kitts and Nevis",
  "AI": "Anguilla",
  "LC": "Saint Lucia",
  "MF": "Saint Martin",
  "PM": "Saint Pierre and Miquelon",
  "VC": "Saint Vincent and the Grenadines",
  "SM": "San Marino",
  "ST": "São Tomé and Príncipe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia",
  "VN": "Vietnam",
  "SI": "Slovenia",
  "SO": "Somalia",
  "ZA": "South Africa",
  "ZW": "Zimbabwe",
  "ES": "Spain",
  "SS": "South Sudan",
  "SD": "Sudan",
  "EH": "Western Sahara",
  "SR": "Suriname",
  "SJ": "Svalbard and Jan Mayen",
  "SZ": "Eswatini",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syria",
  "TJ": "Tajikistan",
  "TH": "Thailand",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "AE": "United Arab Emirates",
  "TN": "Tunisia",
  "TR": "Türkiye",
  "TM": "Turkmenistan",
  "TC": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "MK": "North Macedonia",
  "EG": "Egypt",
  "GB": "United Kingdom",
  "GG": "Guernsey",
  "JE": "Jersey",
  "IM": "Isle of Man",
  "TZ": "Tanzania",
  "US": "United States",
  "VI": "United States Virgin Islands",
  "BF": "Burkina Faso",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VE": "Venezuela",
  "WF": "Wallis and Futuna",
  "WS": "Samoa",
  "YE": "Yemen",
  "ZM": "Zambia",
  "AF": "Afghanistan",
  "AO": "Angola",
  "AL": "Albania",
  "AD": "Andorra",
  "AR": "Argentina",
  "AM": "Armenia",
  "AS": "American Samoa",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BE": "Belgium",
  "BD": "Bangladesh",
  "BH": "Bahrain",
  "BS": "Bahamas",
  "BA": "Bosnia and Herzegovina",
  "BZ": "Belize",
  "BM": "Bermuda",
  "BO": "Bolivia",
  "BR": "Brazil",
  "BB": "Barbados",
  "BN": "Brunei",
  "BT": "Bhutan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "DZ": "Algeria",
  "IO": "British Indian Ocean Territory",
  "SB": "Solomon Islands",
  "VG": "British Virgin Islands",
  "XU": "N. Cyprus"
}

/** All resolvable countries, sorted by name — used for the visit autocomplete. */
export const COUNTRIES: CountryMeta[] = [
  {
    "iso2": "AF",
    "name": "Afghanistan",
    "region": "Asia"
  },
  {
    "iso2": "AX",
    "name": "Åland Islands",
    "region": "Europe"
  },
  {
    "iso2": "AL",
    "name": "Albania",
    "region": "Europe"
  },
  {
    "iso2": "DZ",
    "name": "Algeria",
    "region": "Africa"
  },
  {
    "iso2": "AS",
    "name": "American Samoa",
    "region": "Oceania"
  },
  {
    "iso2": "AD",
    "name": "Andorra",
    "region": "Europe"
  },
  {
    "iso2": "AO",
    "name": "Angola",
    "region": "Africa"
  },
  {
    "iso2": "AI",
    "name": "Anguilla",
    "region": "Americas"
  },
  {
    "iso2": "AQ",
    "name": "Antarctica",
    "region": "Antarctic"
  },
  {
    "iso2": "AG",
    "name": "Antigua and Barbuda",
    "region": "Americas"
  },
  {
    "iso2": "AR",
    "name": "Argentina",
    "region": "Americas"
  },
  {
    "iso2": "AM",
    "name": "Armenia",
    "region": "Asia"
  },
  {
    "iso2": "AW",
    "name": "Aruba",
    "region": "Americas"
  },
  {
    "iso2": "AU",
    "name": "Australia",
    "region": "Oceania"
  },
  {
    "iso2": "AT",
    "name": "Austria",
    "region": "Europe"
  },
  {
    "iso2": "AZ",
    "name": "Azerbaijan",
    "region": "Asia"
  },
  {
    "iso2": "BS",
    "name": "Bahamas",
    "region": "Americas"
  },
  {
    "iso2": "BH",
    "name": "Bahrain",
    "region": "Asia"
  },
  {
    "iso2": "BD",
    "name": "Bangladesh",
    "region": "Asia"
  },
  {
    "iso2": "BB",
    "name": "Barbados",
    "region": "Americas"
  },
  {
    "iso2": "BY",
    "name": "Belarus",
    "region": "Europe"
  },
  {
    "iso2": "BE",
    "name": "Belgium",
    "region": "Europe"
  },
  {
    "iso2": "BZ",
    "name": "Belize",
    "region": "Americas"
  },
  {
    "iso2": "BJ",
    "name": "Benin",
    "region": "Africa"
  },
  {
    "iso2": "BM",
    "name": "Bermuda",
    "region": "Americas"
  },
  {
    "iso2": "BT",
    "name": "Bhutan",
    "region": "Asia"
  },
  {
    "iso2": "BO",
    "name": "Bolivia",
    "region": "Americas"
  },
  {
    "iso2": "BA",
    "name": "Bosnia and Herzegovina",
    "region": "Europe"
  },
  {
    "iso2": "BW",
    "name": "Botswana",
    "region": "Africa"
  },
  {
    "iso2": "BV",
    "name": "Bouvet Island",
    "region": "Antarctic"
  },
  {
    "iso2": "BR",
    "name": "Brazil",
    "region": "Americas"
  },
  {
    "iso2": "IO",
    "name": "British Indian Ocean Territory",
    "region": "Africa"
  },
  {
    "iso2": "VG",
    "name": "British Virgin Islands",
    "region": "Americas"
  },
  {
    "iso2": "BN",
    "name": "Brunei",
    "region": "Asia"
  },
  {
    "iso2": "BG",
    "name": "Bulgaria",
    "region": "Europe"
  },
  {
    "iso2": "BF",
    "name": "Burkina Faso",
    "region": "Africa"
  },
  {
    "iso2": "BI",
    "name": "Burundi",
    "region": "Africa"
  },
  {
    "iso2": "KH",
    "name": "Cambodia",
    "region": "Asia"
  },
  {
    "iso2": "CM",
    "name": "Cameroon",
    "region": "Africa"
  },
  {
    "iso2": "CA",
    "name": "Canada",
    "region": "Americas"
  },
  {
    "iso2": "CV",
    "name": "Cape Verde",
    "region": "Africa"
  },
  {
    "iso2": "BQ",
    "name": "Caribbean Netherlands",
    "region": "Americas"
  },
  {
    "iso2": "KY",
    "name": "Cayman Islands",
    "region": "Americas"
  },
  {
    "iso2": "CF",
    "name": "Central African Republic",
    "region": "Africa"
  },
  {
    "iso2": "TD",
    "name": "Chad",
    "region": "Africa"
  },
  {
    "iso2": "CL",
    "name": "Chile",
    "region": "Americas"
  },
  {
    "iso2": "CN",
    "name": "China",
    "region": "Asia"
  },
  {
    "iso2": "CX",
    "name": "Christmas Island",
    "region": "Oceania"
  },
  {
    "iso2": "CC",
    "name": "Cocos (Keeling) Islands",
    "region": "Oceania"
  },
  {
    "iso2": "CO",
    "name": "Colombia",
    "region": "Americas"
  },
  {
    "iso2": "KM",
    "name": "Comoros",
    "region": "Africa"
  },
  {
    "iso2": "CK",
    "name": "Cook Islands",
    "region": "Oceania"
  },
  {
    "iso2": "CR",
    "name": "Costa Rica",
    "region": "Americas"
  },
  {
    "iso2": "HR",
    "name": "Croatia",
    "region": "Europe"
  },
  {
    "iso2": "CU",
    "name": "Cuba",
    "region": "Americas"
  },
  {
    "iso2": "CW",
    "name": "Curaçao",
    "region": "Americas"
  },
  {
    "iso2": "CY",
    "name": "Cyprus",
    "region": "Europe"
  },
  {
    "iso2": "CZ",
    "name": "Czechia",
    "region": "Europe"
  },
  {
    "iso2": "DK",
    "name": "Denmark",
    "region": "Europe"
  },
  {
    "iso2": "DJ",
    "name": "Djibouti",
    "region": "Africa"
  },
  {
    "iso2": "DM",
    "name": "Dominica",
    "region": "Americas"
  },
  {
    "iso2": "DO",
    "name": "Dominican Republic",
    "region": "Americas"
  },
  {
    "iso2": "CD",
    "name": "DR Congo",
    "region": "Africa"
  },
  {
    "iso2": "EC",
    "name": "Ecuador",
    "region": "Americas"
  },
  {
    "iso2": "EG",
    "name": "Egypt",
    "region": "Africa"
  },
  {
    "iso2": "SV",
    "name": "El Salvador",
    "region": "Americas"
  },
  {
    "iso2": "GQ",
    "name": "Equatorial Guinea",
    "region": "Africa"
  },
  {
    "iso2": "ER",
    "name": "Eritrea",
    "region": "Africa"
  },
  {
    "iso2": "EE",
    "name": "Estonia",
    "region": "Europe"
  },
  {
    "iso2": "SZ",
    "name": "Eswatini",
    "region": "Africa"
  },
  {
    "iso2": "ET",
    "name": "Ethiopia",
    "region": "Africa"
  },
  {
    "iso2": "FK",
    "name": "Falkland Islands",
    "region": "Americas"
  },
  {
    "iso2": "FO",
    "name": "Faroe Islands",
    "region": "Europe"
  },
  {
    "iso2": "FJ",
    "name": "Fiji",
    "region": "Oceania"
  },
  {
    "iso2": "FI",
    "name": "Finland",
    "region": "Europe"
  },
  {
    "iso2": "FR",
    "name": "France",
    "region": "Europe"
  },
  {
    "iso2": "GF",
    "name": "French Guiana",
    "region": "Americas"
  },
  {
    "iso2": "PF",
    "name": "French Polynesia",
    "region": "Oceania"
  },
  {
    "iso2": "TF",
    "name": "French Southern and Antarctic Lands",
    "region": "Antarctic"
  },
  {
    "iso2": "GA",
    "name": "Gabon",
    "region": "Africa"
  },
  {
    "iso2": "GM",
    "name": "Gambia",
    "region": "Africa"
  },
  {
    "iso2": "GE",
    "name": "Georgia",
    "region": "Asia"
  },
  {
    "iso2": "DE",
    "name": "Germany",
    "region": "Europe"
  },
  {
    "iso2": "GH",
    "name": "Ghana",
    "region": "Africa"
  },
  {
    "iso2": "GI",
    "name": "Gibraltar",
    "region": "Europe"
  },
  {
    "iso2": "GR",
    "name": "Greece",
    "region": "Europe"
  },
  {
    "iso2": "GL",
    "name": "Greenland",
    "region": "Americas"
  },
  {
    "iso2": "GD",
    "name": "Grenada",
    "region": "Americas"
  },
  {
    "iso2": "GP",
    "name": "Guadeloupe",
    "region": "Americas"
  },
  {
    "iso2": "GU",
    "name": "Guam",
    "region": "Oceania"
  },
  {
    "iso2": "GT",
    "name": "Guatemala",
    "region": "Americas"
  },
  {
    "iso2": "GG",
    "name": "Guernsey",
    "region": "Europe"
  },
  {
    "iso2": "GN",
    "name": "Guinea",
    "region": "Africa"
  },
  {
    "iso2": "GW",
    "name": "Guinea-Bissau",
    "region": "Africa"
  },
  {
    "iso2": "GY",
    "name": "Guyana",
    "region": "Americas"
  },
  {
    "iso2": "HT",
    "name": "Haiti",
    "region": "Americas"
  },
  {
    "iso2": "HM",
    "name": "Heard Island and McDonald Islands",
    "region": "Antarctic"
  },
  {
    "iso2": "HN",
    "name": "Honduras",
    "region": "Americas"
  },
  {
    "iso2": "HK",
    "name": "Hong Kong",
    "region": "Asia"
  },
  {
    "iso2": "HU",
    "name": "Hungary",
    "region": "Europe"
  },
  {
    "iso2": "IS",
    "name": "Iceland",
    "region": "Europe"
  },
  {
    "iso2": "IN",
    "name": "India",
    "region": "Asia"
  },
  {
    "iso2": "ID",
    "name": "Indonesia",
    "region": "Asia"
  },
  {
    "iso2": "IR",
    "name": "Iran",
    "region": "Asia"
  },
  {
    "iso2": "IQ",
    "name": "Iraq",
    "region": "Asia"
  },
  {
    "iso2": "IE",
    "name": "Ireland",
    "region": "Europe"
  },
  {
    "iso2": "IM",
    "name": "Isle of Man",
    "region": "Europe"
  },
  {
    "iso2": "IL",
    "name": "Israel",
    "region": "Asia"
  },
  {
    "iso2": "IT",
    "name": "Italy",
    "region": "Europe"
  },
  {
    "iso2": "CI",
    "name": "Ivory Coast",
    "region": "Africa"
  },
  {
    "iso2": "JM",
    "name": "Jamaica",
    "region": "Americas"
  },
  {
    "iso2": "JP",
    "name": "Japan",
    "region": "Asia"
  },
  {
    "iso2": "JE",
    "name": "Jersey",
    "region": "Europe"
  },
  {
    "iso2": "JO",
    "name": "Jordan",
    "region": "Asia"
  },
  {
    "iso2": "KZ",
    "name": "Kazakhstan",
    "region": "Asia"
  },
  {
    "iso2": "KE",
    "name": "Kenya",
    "region": "Africa"
  },
  {
    "iso2": "KI",
    "name": "Kiribati",
    "region": "Oceania"
  },
  {
    "iso2": "KW",
    "name": "Kuwait",
    "region": "Asia"
  },
  {
    "iso2": "KG",
    "name": "Kyrgyzstan",
    "region": "Asia"
  },
  {
    "iso2": "LA",
    "name": "Laos",
    "region": "Asia"
  },
  {
    "iso2": "LV",
    "name": "Latvia",
    "region": "Europe"
  },
  {
    "iso2": "LB",
    "name": "Lebanon",
    "region": "Asia"
  },
  {
    "iso2": "LS",
    "name": "Lesotho",
    "region": "Africa"
  },
  {
    "iso2": "LR",
    "name": "Liberia",
    "region": "Africa"
  },
  {
    "iso2": "LY",
    "name": "Libya",
    "region": "Africa"
  },
  {
    "iso2": "LI",
    "name": "Liechtenstein",
    "region": "Europe"
  },
  {
    "iso2": "LT",
    "name": "Lithuania",
    "region": "Europe"
  },
  {
    "iso2": "LU",
    "name": "Luxembourg",
    "region": "Europe"
  },
  {
    "iso2": "MO",
    "name": "Macau",
    "region": "Asia"
  },
  {
    "iso2": "MG",
    "name": "Madagascar",
    "region": "Africa"
  },
  {
    "iso2": "MW",
    "name": "Malawi",
    "region": "Africa"
  },
  {
    "iso2": "MY",
    "name": "Malaysia",
    "region": "Asia"
  },
  {
    "iso2": "MV",
    "name": "Maldives",
    "region": "Asia"
  },
  {
    "iso2": "ML",
    "name": "Mali",
    "region": "Africa"
  },
  {
    "iso2": "MT",
    "name": "Malta",
    "region": "Europe"
  },
  {
    "iso2": "MH",
    "name": "Marshall Islands",
    "region": "Oceania"
  },
  {
    "iso2": "MQ",
    "name": "Martinique",
    "region": "Americas"
  },
  {
    "iso2": "MR",
    "name": "Mauritania",
    "region": "Africa"
  },
  {
    "iso2": "MU",
    "name": "Mauritius",
    "region": "Africa"
  },
  {
    "iso2": "YT",
    "name": "Mayotte",
    "region": "Africa"
  },
  {
    "iso2": "MX",
    "name": "Mexico",
    "region": "Americas"
  },
  {
    "iso2": "FM",
    "name": "Micronesia",
    "region": "Oceania"
  },
  {
    "iso2": "MD",
    "name": "Moldova",
    "region": "Europe"
  },
  {
    "iso2": "MC",
    "name": "Monaco",
    "region": "Europe"
  },
  {
    "iso2": "MN",
    "name": "Mongolia",
    "region": "Asia"
  },
  {
    "iso2": "ME",
    "name": "Montenegro",
    "region": "Europe"
  },
  {
    "iso2": "MS",
    "name": "Montserrat",
    "region": "Americas"
  },
  {
    "iso2": "MA",
    "name": "Morocco",
    "region": "Africa"
  },
  {
    "iso2": "MZ",
    "name": "Mozambique",
    "region": "Africa"
  },
  {
    "iso2": "MM",
    "name": "Myanmar",
    "region": "Asia"
  },
  {
    "iso2": "NA",
    "name": "Namibia",
    "region": "Africa"
  },
  {
    "iso2": "NR",
    "name": "Nauru",
    "region": "Oceania"
  },
  {
    "iso2": "NP",
    "name": "Nepal",
    "region": "Asia"
  },
  {
    "iso2": "NL",
    "name": "Netherlands",
    "region": "Europe"
  },
  {
    "iso2": "NC",
    "name": "New Caledonia",
    "region": "Oceania"
  },
  {
    "iso2": "NZ",
    "name": "New Zealand",
    "region": "Oceania"
  },
  {
    "iso2": "NI",
    "name": "Nicaragua",
    "region": "Americas"
  },
  {
    "iso2": "NE",
    "name": "Niger",
    "region": "Africa"
  },
  {
    "iso2": "NG",
    "name": "Nigeria",
    "region": "Africa"
  },
  {
    "iso2": "NU",
    "name": "Niue",
    "region": "Oceania"
  },
  {
    "iso2": "NF",
    "name": "Norfolk Island",
    "region": "Oceania"
  },
  {
    "iso2": "KP",
    "name": "North Korea",
    "region": "Asia"
  },
  {
    "iso2": "MK",
    "name": "North Macedonia",
    "region": "Europe"
  },
  {
    "iso2": "MP",
    "name": "Northern Mariana Islands",
    "region": "Oceania"
  },
  {
    "iso2": "NO",
    "name": "Norway",
    "region": "Europe"
  },
  {
    "iso2": "OM",
    "name": "Oman",
    "region": "Asia"
  },
  {
    "iso2": "PK",
    "name": "Pakistan",
    "region": "Asia"
  },
  {
    "iso2": "PW",
    "name": "Palau",
    "region": "Oceania"
  },
  {
    "iso2": "PS",
    "name": "Palestine",
    "region": "Asia"
  },
  {
    "iso2": "PA",
    "name": "Panama",
    "region": "Americas"
  },
  {
    "iso2": "PG",
    "name": "Papua New Guinea",
    "region": "Oceania"
  },
  {
    "iso2": "PY",
    "name": "Paraguay",
    "region": "Americas"
  },
  {
    "iso2": "PE",
    "name": "Peru",
    "region": "Americas"
  },
  {
    "iso2": "PH",
    "name": "Philippines",
    "region": "Asia"
  },
  {
    "iso2": "PN",
    "name": "Pitcairn Islands",
    "region": "Oceania"
  },
  {
    "iso2": "PL",
    "name": "Poland",
    "region": "Europe"
  },
  {
    "iso2": "PT",
    "name": "Portugal",
    "region": "Europe"
  },
  {
    "iso2": "PR",
    "name": "Puerto Rico",
    "region": "Americas"
  },
  {
    "iso2": "QA",
    "name": "Qatar",
    "region": "Asia"
  },
  {
    "iso2": "CG",
    "name": "Republic of the Congo",
    "region": "Africa"
  },
  {
    "iso2": "RE",
    "name": "Réunion",
    "region": "Africa"
  },
  {
    "iso2": "RO",
    "name": "Romania",
    "region": "Europe"
  },
  {
    "iso2": "RU",
    "name": "Russia",
    "region": "Europe"
  },
  {
    "iso2": "RW",
    "name": "Rwanda",
    "region": "Africa"
  },
  {
    "iso2": "BL",
    "name": "Saint Barthélemy",
    "region": "Americas"
  },
  {
    "iso2": "SH",
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "region": "Africa"
  },
  {
    "iso2": "KN",
    "name": "Saint Kitts and Nevis",
    "region": "Americas"
  },
  {
    "iso2": "LC",
    "name": "Saint Lucia",
    "region": "Americas"
  },
  {
    "iso2": "MF",
    "name": "Saint Martin",
    "region": "Americas"
  },
  {
    "iso2": "PM",
    "name": "Saint Pierre and Miquelon",
    "region": "Americas"
  },
  {
    "iso2": "VC",
    "name": "Saint Vincent and the Grenadines",
    "region": "Americas"
  },
  {
    "iso2": "WS",
    "name": "Samoa",
    "region": "Oceania"
  },
  {
    "iso2": "SM",
    "name": "San Marino",
    "region": "Europe"
  },
  {
    "iso2": "ST",
    "name": "São Tomé and Príncipe",
    "region": "Africa"
  },
  {
    "iso2": "SA",
    "name": "Saudi Arabia",
    "region": "Asia"
  },
  {
    "iso2": "SN",
    "name": "Senegal",
    "region": "Africa"
  },
  {
    "iso2": "RS",
    "name": "Serbia",
    "region": "Europe"
  },
  {
    "iso2": "SC",
    "name": "Seychelles",
    "region": "Africa"
  },
  {
    "iso2": "SL",
    "name": "Sierra Leone",
    "region": "Africa"
  },
  {
    "iso2": "SG",
    "name": "Singapore",
    "region": "Asia"
  },
  {
    "iso2": "SX",
    "name": "Sint Maarten",
    "region": "Americas"
  },
  {
    "iso2": "SK",
    "name": "Slovakia",
    "region": "Europe"
  },
  {
    "iso2": "SI",
    "name": "Slovenia",
    "region": "Europe"
  },
  {
    "iso2": "SB",
    "name": "Solomon Islands",
    "region": "Oceania"
  },
  {
    "iso2": "SO",
    "name": "Somalia",
    "region": "Africa"
  },
  {
    "iso2": "ZA",
    "name": "South Africa",
    "region": "Africa"
  },
  {
    "iso2": "GS",
    "name": "South Georgia",
    "region": "Antarctic"
  },
  {
    "iso2": "KR",
    "name": "South Korea",
    "region": "Asia"
  },
  {
    "iso2": "SS",
    "name": "South Sudan",
    "region": "Africa"
  },
  {
    "iso2": "ES",
    "name": "Spain",
    "region": "Europe"
  },
  {
    "iso2": "LK",
    "name": "Sri Lanka",
    "region": "Asia"
  },
  {
    "iso2": "SD",
    "name": "Sudan",
    "region": "Africa"
  },
  {
    "iso2": "SR",
    "name": "Suriname",
    "region": "Americas"
  },
  {
    "iso2": "SJ",
    "name": "Svalbard and Jan Mayen",
    "region": "Europe"
  },
  {
    "iso2": "SE",
    "name": "Sweden",
    "region": "Europe"
  },
  {
    "iso2": "CH",
    "name": "Switzerland",
    "region": "Europe"
  },
  {
    "iso2": "SY",
    "name": "Syria",
    "region": "Asia"
  },
  {
    "iso2": "TW",
    "name": "Taiwan",
    "region": "Asia"
  },
  {
    "iso2": "TJ",
    "name": "Tajikistan",
    "region": "Asia"
  },
  {
    "iso2": "TZ",
    "name": "Tanzania",
    "region": "Africa"
  },
  {
    "iso2": "TH",
    "name": "Thailand",
    "region": "Asia"
  },
  {
    "iso2": "TL",
    "name": "Timor-Leste",
    "region": "Asia"
  },
  {
    "iso2": "TG",
    "name": "Togo",
    "region": "Africa"
  },
  {
    "iso2": "TK",
    "name": "Tokelau",
    "region": "Oceania"
  },
  {
    "iso2": "TO",
    "name": "Tonga",
    "region": "Oceania"
  },
  {
    "iso2": "TT",
    "name": "Trinidad and Tobago",
    "region": "Americas"
  },
  {
    "iso2": "TN",
    "name": "Tunisia",
    "region": "Africa"
  },
  {
    "iso2": "TR",
    "name": "Türkiye",
    "region": "Asia"
  },
  {
    "iso2": "TM",
    "name": "Turkmenistan",
    "region": "Asia"
  },
  {
    "iso2": "TC",
    "name": "Turks and Caicos Islands",
    "region": "Americas"
  },
  {
    "iso2": "TV",
    "name": "Tuvalu",
    "region": "Oceania"
  },
  {
    "iso2": "UG",
    "name": "Uganda",
    "region": "Africa"
  },
  {
    "iso2": "UA",
    "name": "Ukraine",
    "region": "Europe"
  },
  {
    "iso2": "AE",
    "name": "United Arab Emirates",
    "region": "Asia"
  },
  {
    "iso2": "GB",
    "name": "United Kingdom",
    "region": "Europe"
  },
  {
    "iso2": "US",
    "name": "United States",
    "region": "Americas"
  },
  {
    "iso2": "UM",
    "name": "United States Minor Outlying Islands",
    "region": "Americas"
  },
  {
    "iso2": "VI",
    "name": "United States Virgin Islands",
    "region": "Americas"
  },
  {
    "iso2": "UY",
    "name": "Uruguay",
    "region": "Americas"
  },
  {
    "iso2": "UZ",
    "name": "Uzbekistan",
    "region": "Asia"
  },
  {
    "iso2": "VU",
    "name": "Vanuatu",
    "region": "Oceania"
  },
  {
    "iso2": "VA",
    "name": "Vatican City",
    "region": "Europe"
  },
  {
    "iso2": "VE",
    "name": "Venezuela",
    "region": "Americas"
  },
  {
    "iso2": "VN",
    "name": "Vietnam",
    "region": "Asia"
  },
  {
    "iso2": "WF",
    "name": "Wallis and Futuna",
    "region": "Oceania"
  },
  {
    "iso2": "EH",
    "name": "Western Sahara",
    "region": "Africa"
  },
  {
    "iso2": "YE",
    "name": "Yemen",
    "region": "Asia"
  },
  {
    "iso2": "ZM",
    "name": "Zambia",
    "region": "Africa"
  },
  {
    "iso2": "ZW",
    "name": "Zimbabwe",
    "region": "Africa"
  }
]

/** Resolve a TopoJSON numeric id to ISO alpha-2 (or null). */
export function iso2FromNumeric(numericId: string | number): string | null {
  return ISO_BY_NUMERIC[String(numericId)]?.iso2 ?? null
}
